name: Minimal setup
on:
  push:
    branches:
      - master

jobs:
  benchmark:
    name: Benchmark build time
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Build with forge
        run: npm run make