name: Minimal setup
on:
  push:
    branches:
      - master

jobs:
  benchmark:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    name: Benchmark build time
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Git
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Build with forge
        run: npm run make